

BEGIN;

SET search_path TO public;


CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS restaurants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT 'My Restaurant',
    phone VARCHAR(50),
    email VARCHAR(255),
    address TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    opens_at VARCHAR(10) DEFAULT '09:00',
    closes_at VARCHAR(10) DEFAULT '23:00',
    max_delivery_radius_km DOUBLE PRECISION DEFAULT 15.0,
    avg_speed_kmh DOUBLE PRECISION DEFAULT 30.0,
    use_platform_drivers BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS drivers (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    email VARCHAR(255),
    vehicle_type VARCHAR(50) DEFAULT 'Motorcycle',
    vehicle_number VARCHAR(50),
    license_number VARCHAR(100),
    address TEXT,
    emergency_contact VARCHAR(50),
    owner_type VARCHAR(20) NOT NULL DEFAULT 'restaurant',
    restaurant_id INTEGER REFERENCES restaurants(id),
    is_platform_driver BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'available',
    current_order_id INTEGER,
    current_latitude DOUBLE PRECISION,
    current_longitude DOUBLE PRECISION,
    assigned_at TIMESTAMPTZ,
    estimated_delivery_at TIMESTAMPTZ,
    estimated_return_at TIMESTAMPTZ,
    driver_available_at TIMESTAMPTZ,
    total_deliveries INTEGER DEFAULT 0,
    active_deliveries INTEGER DEFAULT 0,
    rating DOUBLE PRECISION DEFAULT 5.0,
    on_time_deliveries INTEGER DEFAULT 0,
    late_deliveries INTEGER DEFAULT 0,
    average_delivery_time DOUBLE PRECISION DEFAULT 0.0,
    joined_date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT chk_drivers_owner_type
        CHECK (owner_type IN ('restaurant', 'platform')),
    CONSTRAINT chk_drivers_status
        CHECK (status IN ('available', 'on_delivery', 'returning', 'offline'))
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(256) NOT NULL,
    role VARCHAR(20) NOT NULL,
    restaurant_id INTEGER REFERENCES restaurants(id),
    driver_id VARCHAR(50) REFERENCES drivers(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_login TIMESTAMPTZ,
    CONSTRAINT chk_users_role
        CHECK (role IN ('restaurant_admin', 'driver'))
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(50) NOT NULL,
    customer_email VARCHAR(255),
    delivery_address TEXT NOT NULL,
    notes TEXT,
    payment_method VARCHAR(50) DEFAULT 'Card',
    payment_status VARCHAR(50) DEFAULT 'Pending',
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    subtotal DOUBLE PRECISION DEFAULT 0.0,
    tax DOUBLE PRECISION DEFAULT 0.0,
    delivery_fee DOUBLE PRECISION DEFAULT 4.99,
    total DOUBLE PRECISION DEFAULT 0.0,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    restaurant_id INTEGER REFERENCES restaurants(id),
    driver_id VARCHAR(50) REFERENCES drivers(id),
    assigned_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    estimated_delivery TIMESTAMPTZ,
    driver_pickup_eta DOUBLE PRECISION,
    estimated_delivery_minutes INTEGER,
    estimated_return_minutes INTEGER,
    estimated_round_trip_minutes INTEGER,
    driver_available_again_minutes DOUBLE PRECISION,
    driver_available_at TIMESTAMPTZ,
    CONSTRAINT chk_orders_status
        CHECK (status IN ('pending', 'preparing', 'ready', 'assigned', 'out_for_delivery', 'delivered', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    price DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS routes (
    id VARCHAR(50) PRIMARY KEY,
    driver_id VARCHAR(50) NOT NULL REFERENCES drivers(id),
    restaurant_id INTEGER REFERENCES restaurants(id),
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    total_distance DOUBLE PRECISION DEFAULT 0.0,
    estimated_time INTEGER DEFAULT 0,
    total_orders INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT chk_routes_status
        CHECK (status IN ('active', 'completed', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS route_stops (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id VARCHAR(50) NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
    order_id INTEGER NOT NULL REFERENCES orders(id),
    sequence INTEGER NOT NULL,
    address TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    estimated_arrival TIMESTAMPTZ,
    actual_arrival TIMESTAMPTZ,
    CONSTRAINT chk_route_stops_status
        CHECK (status IN ('pending', 'in_transit', 'delivered')),
    CONSTRAINT uq_route_stops_route_sequence
        UNIQUE (route_id, sequence)
);

CREATE TABLE IF NOT EXISTS settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(100) NOT NULL UNIQUE,
    value TEXT,
    value_type VARCHAR(20) DEFAULT 'string',
    category VARCHAR(50) DEFAULT 'general',
    restaurant_id INTEGER REFERENCES restaurants(id),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT chk_settings_value_type
        CHECK (value_type IN ('string', 'number', 'boolean')),
    CONSTRAINT chk_settings_category
        CHECK (category IN ('general', 'voice', 'map', 'order', 'system'))
);

-- Drivers
CREATE INDEX IF NOT EXISTS idx_drivers_status ON drivers(status);
CREATE INDEX IF NOT EXISTS idx_drivers_owner_type ON drivers(owner_type);
CREATE INDEX IF NOT EXISTS idx_drivers_restaurant_id ON drivers(restaurant_id);

-- Users
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);

-- Orders
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_driver_id ON orders(driver_id);
CREATE INDEX IF NOT EXISTS idx_orders_restaurant_id ON orders(restaurant_id);

-- Order items
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);

-- Routes
CREATE INDEX IF NOT EXISTS idx_routes_status ON routes(status);
CREATE INDEX IF NOT EXISTS idx_routes_driver_id ON routes(driver_id);
CREATE INDEX IF NOT EXISTS idx_routes_restaurant_id ON routes(restaurant_id);

-- Route stops
CREATE INDEX IF NOT EXISTS idx_route_stops_route_id ON route_stops(route_id);
CREATE INDEX IF NOT EXISTS idx_route_stops_order_id ON route_stops(order_id);

-- Settings
CREATE INDEX IF NOT EXISTS idx_settings_key ON settings(key);
CREATE INDEX IF NOT EXISTS idx_settings_category ON settings(category);
CREATE INDEX IF NOT EXISTS idx_settings_restaurant_id ON settings(restaurant_id);

-- Updated-at triggers
DROP TRIGGER IF EXISTS trg_restaurants_set_updated_at ON restaurants;
CREATE TRIGGER trg_restaurants_set_updated_at
BEFORE UPDATE ON restaurants
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_drivers_set_updated_at ON drivers;
CREATE TRIGGER trg_drivers_set_updated_at
BEFORE UPDATE ON drivers
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_orders_set_updated_at ON orders;
CREATE TRIGGER trg_orders_set_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_routes_set_updated_at ON routes;
CREATE TRIGGER trg_routes_set_updated_at
BEFORE UPDATE ON routes
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_settings_set_updated_at ON settings;
CREATE TRIGGER trg_settings_set_updated_at
BEFORE UPDATE ON settings
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

COMMIT;
